def menu():
    print("\n"+ "=" *40)
    print("BANKING MANAGMENT SYSTEM")
    print("=" * 40)
    print("1. Create Account")
    print("2. View Accounts")
    print("3. Search Account")
    print("4. Deposit Money")
    print("5. Withdraw Money")
    print("6. Tranfer Money")
    print("7. Transaction History")
    print("8. Delete Account")
    print("9. Exit")
    print("\n" + "=" * 40)
    print("=" * 40)